plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
nodeLinker: node-modules
npmrcPath: .npmrc
yarnNodePath: ~/.nvm/versions/node/v14.15.4/bin/node
yarnPath: .yarn